const modules=[
{group:'OVERVIEW',id:'dashboard',icon:'▦',name:'Executive Dashboard'},
{group:'SAFETY MANAGEMENT',id:'observations',icon:'◉',name:'Safety Observations',count:128,desc:'Capture, assign and close unsafe acts, conditions and positive observations.'},
{id:'incidents',icon:'⚠',name:'Incidents & Near Miss',count:4,desc:'Manage incident notification, investigation, root cause and corrective actions.'},
{id:'ptw',icon:'▤',name:'Permit to Work',desc:'Geo-reference active permits and identify simultaneous or conflicting work.'},
{id:'inspections',icon:'✓',name:'Inspections & Audits',desc:'Plan inspections, score compliance and track closure of findings.'},
{id:'risk',icon:'◆',name:'Risk Register',desc:'Maintain operational risk controls, owners and residual risk ratings.'},
{group:'FIELD OPERATIONS',id:'equipment',icon:'⚙',name:'Plant & Equipment',desc:'Track inspections, certificates, PWAS, IVMS and fire readiness.'},
{id:'environment',icon:'♧',name:'Environment',desc:'Manage waste, spills, emissions, monitoring and environmental actions.'},
{id:'welfare',icon:'⌂',name:'Welfare & Heat Stress',desc:'Monitor drinking water, shelters, toilets, thermos coverage and heat controls.'},
{id:'emergency',icon:'✚',name:'Emergency Resources',desc:'Map assembly points, fire points, AEDs, spill kits and rescue equipment.'},
{id:'training',icon:'◇',name:'Training & Competency',desc:'Monitor induction, trade competency and training expiry.'},
{group:'PERFORMANCE',id:'contractors',icon:'▥',name:'Contractor Performance',desc:'Compare contractor leading indicators, violations and action closure.'},
{id:'reports',icon:'▧',name:'Reports & Analytics',desc:'Create management reports, trend charts and export-ready datasets.'}];
const nav=document.getElementById('nav');let lastGroup='';modules.forEach(m=>{if(m.group&&m.group!==lastGroup){nav.insertAdjacentHTML('beforeend',`<div class="nav-group">${m.group}</div>`);lastGroup=m.group}nav.insertAdjacentHTML('beforeend',`<button class="nav-item ${m.id==='dashboard'?'active':''}" data-id="${m.id}"><span class="ico">${m.icon}</span>${m.name}${m.count?`<small>${m.count}</small>`:''}</button>`)});
const kpis=[['Open observations','128','↑ 12 this week','◉','#f79009'],['Active permits','43','6 high-risk permits','▤','#1570ef'],['Incident-free days','27','Best: 64 days','✓','#12b76a'],['Overdue actions','19','5 critical priority','!','#f04438'],['Training compliance','94%','↑ 2.4% this month','◇','#7a5af8'],['Equipment compliant','88%','32 pending actions','⚙','#06b6d4']];
document.getElementById('kpiGrid').innerHTML=kpis.map(k=>`<div class="kpi" style="--accent:${k[4]}"><div class="top"><span>${k[0]}</span><div class="icon">${k[3]}</div></div><strong>${k[1]}</strong><em>${k[2]}</em></div>`).join('');
const actions=[['High','Missing edge protection','Phase C · U31','Due today'],['Critical','Expired lifting certificate','Phase B · U38','Overdue 2d'],['Medium','Drinking water replenishment','Phase C · U11','Due today'],['High','Oil leakage – excavator 44703','Phase C · U28','Due tomorrow']];
document.getElementById('actionsList').innerHTML=actions.map(a=>`<div class="action-item"><i class="${a[0].toLowerCase()}"></i><div><b>${a[1]}</b><span>${a[2]}</span></div><time>${a[3]}</time></div>`).join('');
const controls=[['Permit validation','43 active / 3 pending','green','Controlled'],['Heat stress controls','TWL 142 – enhanced breaks','amber','Attention'],['Lifting operations','2 critical lifts planned','amber','Review'],['Emergency access','All routes clear','green','Available'],['Electrical LOTO','1 verification pending','red','Action']];
document.getElementById('controlList').innerHTML=controls.map(c=>`<div class="control-row"><div><b>${c[0]}</b><span>${c[1]}</span></div><span class="badge ${c[2]}">${c[3]}</span></div>`).join('');
new Chart(document.getElementById('riskChart'),{type:'doughnut',data:{labels:['Low','Medium','High','Critical'],datasets:[{data:[48,44,30,6],backgroundColor:['#12b76a','#f79009','#f04438','#7a271a'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'72%',plugins:{legend:{display:false}}}});
document.getElementById('riskLegend').innerHTML=[['Low',48,'#12b76a'],['Medium',44,'#f79009'],['High',30,'#f04438'],['Critical',6,'#7a271a']].map(x=>`<span><b><i style="background:${x[2]}"></i>${x[0]}</b><strong>${x[1]}</strong></span>`).join('');
new Chart(document.getElementById('trendChart'),{type:'line',data:{labels:['Thu','Fri','Sat','Sun','Mon','Tue','Wed'],datasets:[{label:'Reported',data:[21,18,26,17,31,24,28],borderColor:'#1570ef',backgroundColor:'rgba(21,112,239,.08)',fill:true,tension:.35},{label:'Closed',data:[16,22,18,20,25,29,31],borderColor:'#12b76a',tension:.35}]},options:{responsive:true,plugins:{legend:{position:'bottom',labels:{boxWidth:8,font:{size:9}}}},scales:{y:{beginAtZero:true,grid:{color:'#eef1f5'},ticks:{font:{size:9}}},x:{grid:{display:false},ticks:{font:{size:9}}}}}});
let map,geoLayer,allGeo;const phaseColors={A:'#1570ef',B:'#7a5af8',C:'#12b76a',Unknown:'#667085'};
allGeo=window.PROJECT_GEOJSON;map=L.map('map',{zoomControl:true}).setView([24.75,55.4],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);renderGeo('all');
function renderGeo(phase){if(geoLayer)geoLayer.remove();const data={...allGeo,features:allGeo.features.filter(f=>phase==='all'||f.properties.phase===phase)};geoLayer=L.geoJSON(data,{style:f=>({color:phaseColors[f.properties.phase],weight:2,fillColor:phaseColors[f.properties.phase],fillOpacity:.13}),pointToLayer:(f,ll)=>L.circleMarker(ll,{radius:5,color:'#fff',weight:1.5,fillColor:phaseColors[f.properties.phase],fillOpacity:1}),onEachFeature:(f,l)=>l.bindPopup(`<b>${f.properties.name}</b><br>Phase ${f.properties.phase}${f.properties.unit?' · Unit '+f.properties.unit:''}<hr><small>KMZ source: ${f.properties.source_type}. Use “New observation” to create an EHS record for this location.</small>`)}).addTo(map);if(geoLayer.getBounds().isValid())map.fitBounds(geoLayer.getBounds(),{padding:[20,20]})}
document.getElementById('phaseFilter').onchange=e=>renderGeo(e.target.value);
const savedRecords=JSON.parse(localStorage.getItem('dewa3_ehs_records')||'[]');
const sampleRows={observations:[['OBS-2026-0142','Phase C · U11','Welfare','No water available in site toilet','Medium','Open'],['OBS-2026-0141','Phase C · U28','Plant & Equipment','Oil leakage from excavator 44703','High','In Progress'],['OBS-2026-0138','Phase B · U37','Housekeeping','Dismantled modules not secured','Low','Closed']],incidents:[['INC-2026-009','Phase B · Parking','Fire','Water tanker cabin fire','High','In Progress'],['NM-2026-034','Phase C · U18','Near Miss','Dropped hand tool within barricade','Medium','Closed']],ptw:[['PTW-1842','Phase C · U25','Electrical','DCB termination','High','Open'],['PTW-1841','Phase B · U38','Lifting','Inverter lifting','High','Open'],['PTW-1838','Phase A · U12','Excavation','Cable trench','Medium','Closed']],inspections:[['INS-2026-322','Phase C · U28','P&M','Summer readiness campaign','High','Open'],['INS-2026-318','Phase B · U37','Scaffold','Weekly scaffold inspection','Medium','Closed']],risk:[['RSK-028','Project wide','Heat stress','Exposure during summer operations','High','Open'],['RSK-019','Phase C','Vehicle fire','Combustibles stored in cabins','High','In Progress']],equipment:[['EQ-44703','Phase C · U28','Dump Truck','Inspection due','High','Open'],['EQ-13156','Phase C · U31','Pickup','Door lock damaged','Medium','In Progress'],['EQ-90987','Scrapyard','Landfill Compactor','Certificate renewed','Low','Closed']],environment:[['ENV-072','Phase C · U05','Waste','Construction waste accumulation','Medium','Open'],['ENV-068','Batching Plant','Washout','Concrete washout inspection','Low','Closed']],welfare:[['WEL-042','Phase C · U31','Facilities','1 toilet for 120+ workmen','High','Open'],['WEL-039','Phase A · U14','Heat Stress','Thermos ratio verified','Low','Closed']],emergency:[['ER-018','Phase C · U22','Fire Point','Monthly inspection','Low','Closed'],['ER-011','Main Office','AED','Battery replacement due','Medium','Open']],training:[['TRN-244','Project wide','Heat Stress','Toolbox talk','Low','Closed'],['TRN-241','Lifting Team','Competency','Lifting supervisor assessment','High','Open']],contractors:[['CTR-AV','Allied Vision','Score 82%','9 open actions','Medium','Open'],['CTR-AI','Al Islah','Score 74%','14 open actions','High','In Progress']],reports:[['RPT-0726','Project wide','Monthly HSE Report','June 2026','Low','Closed'],['RPT-W28','Project wide','Weekly Dashboard','Week 28','Low','Open']]};
savedRecords.reverse().forEach(r=>sampleRows.observations.unshift([r.ref,`Phase ${r.phase} · ${r.unit}`,r.category,r.description,r.risk,r.status]));
const moduleStats=[['Total records','1,486'],['Open','128'],['Overdue','19'],['Closure rate','91%']];
function openModule(id){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.id===id));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));const mod=modules.find(x=>x.id===id);if(id==='dashboard'){document.getElementById('dashboardPage').classList.add('active');pageTitle.textContent='Executive Dashboard';pageSub.textContent='Live project-wide EHS visibility';setTimeout(()=>map&&map.invalidateSize(),50);return}document.getElementById('modulePage').classList.add('active');pageTitle.textContent=mod.name;pageSub.textContent='DEWA III EHS Management System';moduleTitle.textContent=mod.name;moduleDesc.textContent=mod.desc;moduleEyebrow.textContent=(mod.group||'EHS MODULE');document.getElementById('moduleKpis').innerHTML=moduleStats.map(s=>`<div class="module-stat"><span>${s[0]}</span><strong>${s[1]}</strong></div>`).join('');document.getElementById('moduleHead').innerHTML='<tr><th>Reference</th><th>Location / Owner</th><th>Category</th><th>Description / Metric</th><th>Risk</th><th>Status</th></tr>';renderRows(sampleRows[id]||sampleRows.observations)}
function renderRows(rows){document.getElementById('moduleBody').innerHTML=rows.map(r=>`<tr>${r.map((v,i)=>i===4?`<td><span class="risk-tag ${v}">${v}</span></td>`:i===5?`<td><span class="status-tag ${v.replace(' ','\.')}">${v}</span></td>`:`<td>${i===0?'<b>'+v+'</b>':v}</td>`).join('')}</tr>`).join('')}
nav.onclick=e=>{const b=e.target.closest('.nav-item');if(b)openModule(b.dataset.id)};
const modal=document.getElementById('recordModal');function showModal(){modal.classList.add('show')}function hideModal(){modal.classList.remove('show')}newObsBtn.onclick=showModal;moduleAdd.onclick=showModal;closeModal.onclick=hideModal;cancelModal.onclick=hideModal;recordForm.onsubmit=e=>{e.preventDefault();const els=recordForm.querySelectorAll('select,input,textarea');const rec={ref:'OBS-'+new Date().getFullYear()+'-'+String(Date.now()).slice(-6),phase:els[0].value,unit:els[1].value,category:els[2].value,risk:els[3].value,description:els[4].value,company:els[5].value,target:els[6].value,status:'Open',created:new Date().toISOString()};const saved=JSON.parse(localStorage.getItem('dewa3_ehs_records')||'[]');saved.unshift(rec);localStorage.setItem('dewa3_ehs_records',JSON.stringify(saved));sampleRows.observations.unshift([rec.ref,`Phase ${rec.phase} · ${rec.unit}`,rec.category,rec.description,rec.risk,rec.status]);hideModal();recordForm.reset();toast.textContent='Record saved in this browser';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)};
document.getElementById('refreshBtn').onclick=()=>{toast.textContent='Dashboard refreshed';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)};
document.getElementById('menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');document.getElementById('tableSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#moduleBody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')};
document.getElementById('globalSearch').onkeydown=e=>{if(e.key==='Enter'){const q=e.target.value.toUpperCase();const f=allGeo?.features.find(x=>x.properties.name.toUpperCase().includes(q));if(f){openModule('dashboard');const l=geoLayer.getLayers().find(l=>l.feature?.id===f.id);if(l){map.fitBounds(l.getBounds?l.getBounds():L.latLngBounds([l.getLatLng()]));l.openPopup()}}else{toast.textContent='No matching project location';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}}};